apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: object-detection-app
  name: object-detection-app
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: object-detection-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: object-detection-app
        deploymentconfig: object-detection-app
    spec:
      containers:
      - env:
        - name: OBJECT_DETECTION_URL
          value: http://object-detection-rest:8080/predictions
        - name: USERNAME
          value: user1
        image: "image-registry.openshift-image-registry.svc:5000/cicd/object-detection-app:2022-11-14-08-30-05"
        imagePullPolicy: Always
        name: object-detection-app
        ports:
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
